# https://github.com/pmarsceill/just-the-docs
remote_theme: pmarsceill/just-the-docs

logo: "/assets/images/logo.png"

# Aux links for the upper right navigation
aux_links:
  "EN":
    https://fmgarage.github.io/fx-reports-doc-en/
  "FMGARAGE Homepage":
    - "//fmgarage.com"
